services:
  - type: web
    name: fyp2-mds16-backend
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.5-flash-lite
